### ISSUE TITLE
Make script behaviour more clear

### ISSUE THREAD

**Issue by validname** [s-kostyaev/stash-mirror-with-key#1]
It would be better to know the reason why the script couldn't make push.
I suppose that checking exit code and possible error messages from invoking git gives a flag that there was an error. Maybe in this case mailing the error to the user doing commit is the option.

And I have a question whether I have to add protocol prefix 'ssh://' to first line of parameters or not?

**Comment by s-kostyaev** [comment]
Fixed. View readme.
